apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shahlaa

resources:
  - deployment.yml
  - secret.yml
  
images:
  - name: store-server
    newName: mohammaddocker/medusa-shahlaa-server
    newTag: 0.0.6
  - name: store-admin
    newName: mohammaddocker/medusa-shahlaa-admin
    newTag: 0.0.6