apiVersion: v1
kind: Service
metadata:
  name: medusa-shahlaa-server-service
spec:
  selector:
    app: medusa-shahlaa-server # Match labels from the deployments
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: medusa-shahlaa-admin-service
spec:
  selector:
    app: medusa-shahlaa-admin # Match labels from the deployments
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shahlaa-admin-certificate
spec:
  commonName: shahlaa-admin.bnei.dev
  secretName: shahlaa-admin-certificate-secret
  dnsNames:
    - "shahlaa-admin.bnei.dev"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: admin-rewrite-rule
spec:
  replacePathRegex:
    regex: ^/(.*)$
    replacement: /index.html

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: shahlaa-admin-server
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`shahlaa-admin.bnei.dev`)
      services:
        - kind: Service
          name: medusa-shahlaa-admin-service
          port: 3000
      # middlewares:
      #   - name: admin-rewrite-rule
  tls:
    secretName: shahlaa-admin-certificate-secret
