apiVersion: v1
kind: Service
metadata:
  name: medusa-shahlaa-server-service
spec:
  selector:
    app: medusa-shahlaa-server # Match labels from the deployments
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shahlaa-server-certificate
spec:
  commonName: shahlaa-server.bnei.dev
  secretName: shahlaa-server-certificate-secret
  dnsNames:
    - "shahlaa-server.bnei.dev"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: shahlaa-server-server
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`shahlaa-server.bnei.dev`)
      services:
        - kind: Service
          name: medusa-shahlaa-server-service
          port: 3000
  tls:
    secretName: shahlaa-server-certificate-secret
