name: front-ci

on:
  push:
    branches:
      - main
    paths:
      - storefront/**
      - '!storefront/kustomize/**'
  workflow_dispatch:
    

env:
  IMAGE_NAME: medusa-shahlaa-front
  MEDUSA_BACKEND_URL: https://shahlaa-server.bnei.dev
  PUBLIC_URL: https://shahlaa-front.bnei.dev

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: storefront

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Extract version from package.json
        id: extract_version
        run: |
          echo VERSION=$(jq -r .version package.json) >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: storefront
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          build-args: MEDUSA_BACKEND_URL=${{ env.MEDUSA_BACKEND_URL }}, PUBLIC_URL=${{ env.PUBLIC_URL }}
